title: Giuseppe Carbonara 
logo: "/images/profilo1.png?raw=true" 
description: >
  
  I`m Giuseppe, 32 years old Junior Data Scientist with a background in cognitive science, a master degree in human-Computer interaction and a 2nd level Master degree in<a href="https://md2sl-eng.imtlucca.it/"> Data Science and Statistical Learning</a> 
  at the University of Florence and IMT (School for Advanced Studies Lucca).
  This page contains some of the Machine Learning projects I developed.
  
  <br><br>

  <a href="https://github.com/gobrac/Portfolio/blob/988005e6f09d42d77e8d92915c966c03b9551cef/CV_DS_3.pdf">View my CV</a>   
  <br>
  <a href="https://www.linkedin.com/in/gobrac/">View my LinkedIn Profile</a> 
  <a href="  https://scholar.google.com/citations?hl=it&user=ARRb0gIAAAAJ&scilu=&scisig=AMD79ooAAAAAYi8crHa_nThmXh_seWEnRQwWxT_LcOC1&gmla=AJsN-F4oKS7oY1cZPMjCWhXty0VKpE6yflUsl5l1KZLghFFcNIJQWKPIywaMtBMBz0louP2tOJZgfKLkhVqX_SrPcaPkkpgLdlSwwZ9eofLNLzM3bM6Hfpo&sciund=5864651334147819953
">Publications</a> 
  
theme: jekyll-theme-minimal
