title: Giuseppe Carbonara # your name (or website title) here
logo: "/images/profilo1.png?raw=true" # your photo (or logo) here
description: >
  I`m Giuseppe, 32 years old Data Scientist student of the 2nd level Master course in Data Science and Statistical Learning at the University of Florence and IMT School for Advanced Studies Lucca.
  I have a Master degree in human-Computer interaction with a background in psychology and a multi-disciplinary curriculum.

  During the last two years, I worked as UX designer/Researcher in the R&D team of Re:Lab s.r.l. at Reggio Emilia (Italy); My role encompassed the whole design process, from the preliminary exploratory stages of the user research to the data analysis and the creation of prototypes ready to be developed or tested, keeping the users' needs always in mind.
  I worked in multiple industries like automotive, banking sector (Intesa SanPaolo) and lighting manufacturing (Philips lighting), always in cross-disciplinary teams and with multiple international stakeholders. 

  My studies and work have widely prepared me in quantitative and qualitative methodologies for user research in the field of User Experience design, Now with a 2nd level master in Data Science, I want to deepen my quantitative research and data analysis skills with a focus on Machine Learning methodologies for business and health sciences.
  I have excellent knowledge of quantitative data analysis in Python and R programming and data visualization tools as Tableau,  as well as in qualitative research methodologies as interviews and focus groups. I am a proficient user of Adobe Creative Suite (PS, Illustrator, InDesign) and prototyping tools (as Axure, XD),

  I like to constantly challenge myself and I am looking forward to working with you!


  <a href="https://www.linkedin.com/in/gobrac/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-Z7VG95QDQ5 # your Google Analytics tracking ID here
