title: Giuseppe Carbonara # your name (or website title) here
logo: "/images/profilo1.png?raw=true" # your photo (or logo) here
description: >
  I`m Giuseppe, 32 years old Data Scientist student of the 2nd level Master course in <a href="https://md2sl.imtlucca.it/"> Data Science and Statistical Learning</a>  at the University of Florence/IMT School for Advanced Studies Lucca.
  I have a Master degree in human-Computer interaction with a background in psychology and a multi-disciplinary curriculum.

  During the last two years, I worked as UX designer/Researcher in the R&D team of Re:Lab s.r.l. at Reggio Emilia (Italy); 
  My role encompassed the whole design process, from the preliminary exploratory stages to the data analysis and the creation of prototypes ready to be developed or tested, keeping the users' needs always in mind.
  I worked in multiple industries like automotive, banking sector (Intesa SanPaolo) and lighting manufacturing (Philips lighting), in cross-disciplinary teams and with multiple international stakeholders. 

  This page contains some of the Machine Learning projects I developed.
  
  <br><br>

  <a href="https://github.com/gobrac/Portfolio/blob/a7ac8b11e3921fa4e5ebe6bde3fac78dd831e222/About.md">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-Z7VG95QDQ5 # your Google Analytics tracking ID here
